### ISSUE TITLE
compatiblity issue with older Node found in some linux distros

### ISSUE THREAD

**Issue by rjp421** [rjp421/express-socketio-clicktest#1]
```
kali@kali:~/www-test/express-socketio-clicktest$ node index.js 
/home/kali/www-test/express-socketio-clicktest/index.js:71
    connectedUsersObj[clientId]?.broadcast.emit('click', {x, y});
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
kali@kali:~/www-test/express-socketio-clicktest$ node --version
v12.22.9
```

**Comment by rjp421** [comment]
?. is a recently added shortcut to check if the object exists, i will need to check manually
